### PR TITLE
Updated versions

### PR DESCRIPTION
**Pull request by serranoarevalo**

### CODE REVIEW

**Comment by lfades** [comment]
Thanks 👍

**Comment by serranoarevalo** [comment]
Sweet, let's see how it goes.

**Comment by lfades** [comment]
I'll publish the new version in 30 minutes, seems like I also need to update some types.

**Comment by lfades** [comment]
@serranoarevalo the new version is up!.

**Comment by serranoarevalo** [comment]
Thanks a lot!!

**Pull request merged**
