### PR TITLE
Hooks support, AppTree, Tests

### PR DESCRIPTION
**Pull request by qw-in**
Try out this pr [`@qw-in/next-with-apollo`](https://www.npmjs.com/package/@qw-in/next-with-apollo)

# Hooks support
As per the discussion in #74, hooks were already kind of working. However I have switched over to using `@apollo/react-ssr` so hopefully `apollo-react` is now optional.

# AppTree
Another issue people may have been running into is next built in hooks returning null (notably `useRouter`). This is due to the context providers not being in the tree when running getDataFromTree as discussed in #78 

# Integration tests
Before updating anything I spent some time and tried to add some integration tests. They are super slow and certainly not optimal but hopefully useful. Considering this library probably won't get updated very often it is probably not worth addressing unless the next team decides to publish their test utils.

To run the suite

```
yarn integration
```

This will
1. Build the source
1. Build the fixture
1. Run the tests

_if anyone knows why this is breaking in codesandbox please let me know. Working fine locally_
https://codesandbox.io/s/next-with-apollo-y8ltr

### CODE REVIEW

**Comment by silesky** [comment]
Thank you for making this more battle tested.

**Comment by qw-in** [comment]
@lfades is there anything I can do to help get this merged?

**Comment by lfades** [comment]
@qw-in Sorry for the response. I'll review it tomorrow, This PR will most likely require readme changes, right? you can use this: https://github.com/lfades/next-with-apollo/pull/63/files#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by itsmepetrov** [comment]
I've tried to set up this PR in my project and got the following error:

```
GraphQL error occurred [getDataFromTree]
Invariant Violation: ReactDOMServer does not yet support Suspense.
```

This error occurs only in browser when I change pages by clicking on links.

My config:

```js
// withApollo.js
import withApollo from '@qw-in/next-with-apollo';
import { ApolloClient } from 'apollo-client'
import { InMemoryCache } from 'apollo-cache-inmemory'
import { HttpLink } from 'apollo-link-http'
import { setContext } from 'apollo-link-context'
import fetch from 'isomorphic-unfetch'
import cookie from 'cookie'
 
function getToken(req) {
  const cookies = cookie.parse(req ? req.headers.cookie || '' : document.cookie)
  return cookies.token
}

export default withApollo(
  ({ ctx, headers, initialState }) => {
    const isBrowser = typeof window !== 'undefined'

    const httpLink = new HttpLink({
      uri: 'http://localhost:1337/graphql',
      credentials: 'same-origin',
      fetch: !isBrowser && fetch
    })

    const authLink = setContext((request, { headers }) => {
      const token = isBrowser ? getToken() : getToken(ctx.req)
      return {
        headers: {
          ...headers,
          authorization: token ? `Bearer ${token}` : ''
        }
      }
    })

    return new ApolloClient({
      connectToDevTools: isBrowser,
      ssrMode: !isBrowser, // Disables forceFetch on the server (so queries are only run once)
      link: authLink.concat(httpLink),
      cache: new InMemoryCache().restore(initialState || {})
    })
  }
);
```

```js
// _app.js
import App from "next/app";
import React from "react";
import withApollo from "../lib/withApollo";
import { ApolloProvider } from "@apollo/react-hooks";

class MyApp extends App {
  render() {
    const { Component, pageProps, apollo } = this.props;
    return (
        <ApolloProvider client={apollo}>
          <Component {...pageProps} />
        </ApolloProvider>
    );
  }
}

export default withApollo(MyApp);
```

**Comment by qw-in** [comment]
Likely related to https://github.com/zeit/next.js/issues/8289

**Comment by lfades** [comment]
@qw-in I added some changes, can you check those changes and make sure it looks okay to you too 🙏

**Comment by qw-in** [comment]
@lfades looks good to me! Thanks! I also updated `@qw-in/next-with-apollo@5.0.1`

**Comment by lfades** [comment]
Published to `4.3.0`, thank you for the PR 💯

**Pull request merged**
