### PR TITLE
getDataFromTree only for SSR

### PR DESCRIPTION
**Pull request by kuznetsov-online**

### CODE REVIEW

**Comment by kuznetsov-online** [comment]
but why? if you use it (await getDataFromTree) in browser - you have no any 'loading' states in first render

**Comment by lfades** [comment]
@kuznetsov-online I understand what you want, but this would be a breaking change, I'm gonna do something different instead:

For v3 I'm adding an option that will allow you to remove `getDataFromTree` on SSR or browser, this should let you choose the behaviour you want 💃

**Comment by lfades** [comment]
Closed in favor of #15 

@kuznetsov-online to remove `getDataFromTree` from the browser first install the new version (3.0) and do the following:

```js
withApollo(
  new ApolloClient(...),
  {
    getDataFromTree: 'ssr'
  }
)
```

**Comment by lfades** [comment]
@kuznetsov-online I updated my previous comment to follow the version 3.1.0 that contains an important fix, sorry for the inconvenience 🔨

**Pull request closed without merging**
